kafka:
  common:
    bootstrap-servers: "localhost:9092"
    schema-registry-url-key: "schema.registry.url"
    schema-registry-url: "http://localhost:8081"

  topic:
    default:
      consumer:
        group-id: test-consumer-group

  topics:

    topic-configs:
      user-events:
        num-of-partitions: 11
        replication-factor: 10
        producer:
          value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
          acks: all
        consumer:
          value-deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
          enable-auto-commit: false
          additional-props:
            specific.json.value.type: true
            json.value.type: az.kon.academy.broker.example.model.UserEvent
      notification-events:
        num-of-partitions: 6
        replication-factor: 1
        producer:
          value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
          acks: all
        consumer:
          value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
          additional-props:
            specific.avro.reader: true
server:
  port: 5050

logging:
  level:
    az.kon.academy.broker: debug
