kafka:
  common:
    bootstrap-servers: "localhost:9092"
    schema-registry-url-key: "schema.registry.url"
    schema-registry-url: "http://localhost:8081"

  topic:
    default:
      consumer:
        group-id: test-consumer-group

  topics:

    topic-configs:
      user-events:
        num-of-partitions: 11
        replication-factor: 10
        producer:
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          acks: all
        consumer:
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          additional-props:
            spring.json.trusted.packages: "*"
            spring.json.value.default.type: az.kon.academy.broker.example.model.UserEvent

server:
  port: 5050

logging:
  level:
    az.kon.academy.broker: debug
